apiVersion: spawn-eigr.io/v1
kind: ActorHost
metadata:
  labels:
    app: postalcode-spawn-demo
  name: postalcode-spawn-demo
  annotations:
    spawn-eigr.io/actor-system: spawn-demo
    spawn-eigr.io/app-port: "8091"
spec:
  selector:
    app: postalcode-spawn-demo
  host:
    image: image-registry.openshift-image-registry.svc:5000/spawn/postalcode-spawn-demo
    ports:
      - name: "http"
        containerPort: 8080
      - name: "actor"
        containerPort: 8091
