apiVersion: spawn-eigr.io/v1
kind: ActorHost
metadata:
  labels:
    app: postalcode-spawn-demo
  name: postalcode-spawn-demo
  annotations:
    spawn-eigr.io/actor-system: spawn-demo
spec:
  selector:
    app: postalcode-spawn-demo
  host:
    image: postalcode-spawn-demo:latest
    ports:
      - name: "http"
        containerPort: 8080
      - name: "actor"
        containerPort: 8091
