apiVersion: v1
kind: Service
metadata:
  labels:
    app: postalcode-spawn-demo
  name: postalcode-spawn-demo
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: postalcode-spawn-demo
